// app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import LoginModal from "./components/Modals/LoginModal";
import ForgotModal from "./components/Modals/ForgotModal";
import VerifyModal from "./components/Modals/VerifyModal";
import ForgotPasswordModal from "./components/Modals/PasswordResetModal";
import ToasterProvider from "./providers/ToastProvider";
import getCurrentUser from "./actions/getCurrentUser";

import ClientPayPalProvider from "@/app/providers/ClientPayPalProvider";

// Import Satoshi as a local font
const satoshi = localFont({
  src: [
    {
      path: "/fonts/Satoshi-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Satoshi-Medium.woff",
      weight: "500",
      style: "medium",
    },
    {
      path: "/fonts/Satoshi-Bold.woff",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${satoshi.variable} overflow-x-hidden`}>
        <ToasterProvider />

        <LoginModal />
        <ForgotModal />
        <VerifyModal />
        <ForgotPasswordModal />
        <Header currentUser={currentUser} />
        <ClientPayPalProvider>{children}</ClientPayPalProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
